package top.getidea.config.common.entity.userManager;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;

/**
 * @TableName sys_role_user
 */
@Data
@TableName("sys_role_user")
public class RoleUser implements Serializable {
    /**
     * 
     *
     * @mbg.generated Thu Jan 28 12:44:31 CST 2021
     */
    @TableField("role_id")
    private Integer roleId;

    /**
     * 
     *
     * @mbg.generated Thu Jan 28 12:44:31 CST 2021
     */
    @TableField("user_id")
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role_user
     *
     * @mbg.generated Thu Jan 28 12:44:31 CST 2021
     */
    private static final long serialVersionUID = 1L;
}