package top.getidea.config.common.entity.userManager;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.io.Serializable;

/**
 * @author getidea
 * @TableName sys_role
 */
@Data
@TableName("sys_role")
public class Role implements Serializable {
    /**
     * 
     *
     * @mbg.generated Thu Jan 28 12:42:30 CST 2021
     */
    @TableId
    private Integer id;

    /**
     * 
     *
     * @mbg.generated Thu Jan 28 12:42:30 CST 2021
     */
    @TableField("rolename")
    private String rolename;

    /**
     * 
     *
     * @mbg.generated Thu Jan 28 12:42:30 CST 2021
     */
    @TableField("defaultLink")
    private String defaultLink;

    /**
     * 
     *
     * @mbg.generated Thu Jan 28 12:42:30 CST 2021
     */
    @JsonIgnore
    @TableField("status")
    private String status;

    /**
     * 
     *
     * @mbg.generated Thu Jan 28 12:42:30 CST 2021
     */
    @TableField("description")
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role
     *
     * @mbg.generated Thu Jan 28 12:42:30 CST 2021
     */
    private static final long serialVersionUID = 1L;
}