package top.getidea.config.common.entity.userManager;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * @author getidea
 * @TableName sys_user
 */
@Data
@TableName("sys_user")
public class User implements Serializable {
    /**
     * 用户主键
     *
     * @mbg.generated Wed Jan 27 17:38:32 CST 2021
     */
    @TableId
    private Integer id;

    /**
     * 用户名
     *
     * @mbg.generated Wed Jan 27 17:38:32 CST 2021
     */
    @TableField("username")
    private String username;

    /**
     * 用户密码
     *
     * @mbg.generated Wed Jan 27 17:38:32 CST 2021
     */
    @TableField("password")
    @JsonIgnore
    private String password;

    /**
     * 真实姓名
     *
     * @mbg.generated Wed Jan 27 17:38:32 CST 2021
     */
    @TableField("realname")
    private String realname;

    /**
     * 用户状态
     *
     * @mbg.generated Wed Jan 27 17:38:32 CST 2021
     */
    @TableField("status")
    @JsonIgnore
    private Integer status;

    /**
     * 
     *
     * @mbg.generated Wed Jan 27 17:38:32 CST 2021
     */
    @TableField("create_id")
    private Integer createId;

    /**
     * 
     *
     * @mbg.generated Wed Jan 27 17:38:32 CST 2021
     */
    @TableField("create_time")
    private Date createTime;

    /**
     * 
     *
     * @mbg.generated Wed Jan 27 17:38:32 CST 2021
     */
    @TableField("modify_id")
    private Integer modifyId;

    /**
     * 
     *
     * @mbg.generated Wed Jan 27 17:38:32 CST 2021
     */
    @TableField("modify_time")
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbg.generated Wed Jan 27 17:38:32 CST 2021
     */
    private static final long serialVersionUID = 1L;
}